# Generated by Django 3.0.7 on 2024-01-29 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='display',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('staff', 'STAFF'), ('support', 'SUPPORT'), ('admin', 'ADMIN')], max_length=50),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(choices=[('patient', 'patient'), ('staff', 'staff')], max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('roles', models.ManyToManyField(related_name='permissions', to='users.Roles')),
            ],
        ),
    ]
