# Generated by Django 3.0.7 on 2024-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240129_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(choices=[('create', 'CREATE'), ('read', 'READ'), ('update', 'UPDATE'), ('delete', 'DELETE')], max_length=100, unique=True),
        ),
    ]
